name: Main
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Verify with Maven
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: mvn verify

      - name: unit test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage
          path: ./target/site/jacoco-unit-test-coverage-report

      - name: integration test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-coverage
          path: ./target/site/jacoco-integration-test-coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.2.2
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
